
export const RBAC_CONSTANTS = {
  PAGINATION: {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 20,
    MAX_LIMIT: 100,
  },
  PASSWORD: {
    MIN_LENGTH: 8,
    MAX_LENGTH: 128,
    SALT_ROUNDS: 12,
    MAX_FAILED_ATTEMPTS: 5,
  },
  TOKEN: {
    ACCESS_TOKEN_COOKIE: 'access_token',
    REFRESH_TOKEN_COOKIE: 'refresh_token',
  },
} as const;

export const AUDIT_ACTIONS = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  SOFT_DELETE: 'SOFT_DELETE',
  RESTORE: 'RESTORE',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LOGIN_FAILED: 'LOGIN_FAILED',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',
  PASSWORD_RESET: 'PASSWORD_RESET',
  ROLE_ASSIGN: 'ROLE_ASSIGN',
  ROLE_REVOKE: 'ROLE_REVOKE',
  PERMISSION_ASSIGN: 'PERMISSION_ASSIGN',
  PERMISSION_REVOKE: 'PERMISSION_REVOKE',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED: 'ACCOUNT_UNLOCKED',
  ACCOUNT_ACTIVATED: 'ACCOUNT_ACTIVATED',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',
} as const;

/** Injection tokens for repository interfaces */
export const REPOSITORY_TOKENS = {
  USER_REPOSITORY: Symbol('IUserRepository'),
  ROLE_REPOSITORY: Symbol('IRoleRepository'),
  PERMISSION_REPOSITORY: Symbol('IPermissionRepository'),
  AUDIT_REPOSITORY: Symbol('IAuditRepository'),
  REFRESH_TOKEN_REPOSITORY: Symbol('IRefreshTokenRepository'),
} as const;
